# Generated by Django 5.0 on 2023-12-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='shopicons/')),
            ],
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Shop Name')),
                ('shop_name_local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shop Name Local')),
                ('shop_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Shop Address')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number (Username)')),
                ('whatsapp_number', models.CharField(blank=True, default='91', max_length=20, null=True, verbose_name='Whatsapp Number (With Country Code)')),
                ('shop_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Shop Code')),
                ('shop_logo', models.ImageField(blank=True, upload_to='shop_logos/', verbose_name='Shop Logo (494x86)')),
                ('shop_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shop URL')),
                ('expired_date', models.DateField(verbose_name='Expired Date')),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seo Title')),
                ('pay_type', models.CharField(blank=True, choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('premium', 'Premium')], max_length=50, null=True, verbose_name='Pay Type')),
                ('seo_image', models.ImageField(blank=True, upload_to='seo_images/', verbose_name='Seo Image')),
                ('background_sound', models.FileField(blank=True, null=True, upload_to='background_sounds/', verbose_name='Background Sound')),
                ('shop_map_url', models.URLField(blank=True, null=True, verbose_name='Shop Map URL')),
                ('social_icons_url', models.URLField(blank=True, null=True, verbose_name='Social Icons Url')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='Seo Description')),
                ('city_names', models.TextField(blank=True, null=True, verbose_name='City Names')),
                ('menu_brochure', models.FileField(blank=True, null=True, upload_to='menu_brochures/', verbose_name='Menu / Brochure')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, to='dashboard.category')),
                ('social_icons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.icon')),
                ('shoptype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.shoptype')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='shoptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shoptype'),
        ),
    ]
