# Generated by Django 5.0 on 2023-12-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_icon_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='icon',
        ),
    ]
