# Generated by Django 5.0 on 2023-12-21 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_shop_social_icons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='shop',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop'),
            preserve_default=False,
        ),
    ]
