# Generated by Django 5.0 on 2023-12-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_icon_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(choices=[('faceook', 'facebook')], max_length=100),
        ),
    ]
