# Generated by Django 5.0 on 2023-12-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('whatsapp', 'whatsapp')], max_length=100),
        ),
    ]
