# Generated by Django 5.0 on 2024-01-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(blank=True, choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('whatsapp', 'whatsapp')], max_length=100, null=True),
        ),
    ]
